# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessLogDataProvider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.ProtoProcessLogEntryContainer_pb2 as ProtoProcessLogEntryContainer__pb2
import proto.ProcessLogConfiguration_pb2 as ProcessLogConfiguration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cProcessLogDataProvider.proto\x12\x0fProtoProcessLog\x1a#ProtoProcessLogEntryContainer.proto\x1a\x1dProcessLogConfiguration.proto2\x93\x01\n\x16ProcessLogDataProvider\x12y\n\x1bRequestProcessLogDataStream\x12(.ProtoProcessLog.ProcessLogConfiguration\x1a..ProtoProcessLog.ProtoProcessLogEntryContainer0\x01')



_PROCESSLOGDATAPROVIDER = DESCRIPTOR.services_by_name['ProcessLogDataProvider']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSLOGDATAPROVIDER._serialized_start=118
  _PROCESSLOGDATAPROVIDER._serialized_end=265
# @@protoc_insertion_point(module_scope)
