networks:
  ml_net:
    driver: bridge

volumes:
  influx_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./docker-volumes/influx/data
  # influx_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./docker-volumes/influx/config
  # telegraf_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./docker-volumes/telegraf/config
  # chronograf:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./docker-volumes/chronograf
  # mosquitto_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./docker-volumes/mosquitto/config
  mosquitto_log:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./docker-volumes/mosquitto/log
  mosquitto_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./docker-volumes/mosquitto/data

services:
  influxdb:
    image: influxdb:1.8.10-alpine
    networks:
      - ml_net
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - ./docker-volumes/influxdb/config:/etc/influxdb

  telegraf:
    image: telegraf:alpine
    networks:
      - ml_net
    volumes:
      - ./docker-volumes/telegraf/config:/etc/telegraf
    depends_on:
      - influxdb
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - ml_net
    ports:
      - 1883:1883
    volumes:
      - ./docker-volumes/mosquitto/config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
      - mosquitto_data:/mosquitto/data

  chronograf:
    image: chronograf:alpine
    networks: 
      - ml_net
    ports:
      - 8888:8888
    volumes:
      - ./docker-volumes/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
      
  preprocessor:
    build: 
      dockerfile: ./components/preprocessor/Dockerfile
      context: ./
    networks:
      - ml_net
    depends_on:
      - influxdb
  
  modelserver:
    build:
      dockerfile: ./components/modelserver/Dockerfile
      context: ./
    networks:
      - ml_net
    depends_on:
      - influxdb