networks:
  ml_net:
    driver: bridge

volumes:
  influx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/influx_data
  influx_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/influx_config
  telegraf_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/telegraf_config

services:
  influxdb:
    build: influxdb
    networks:
      - ml_net
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2

  telegraf:
    build: telegraf
    networks:
      - ml_net
    volumes:
      - telegraf_config:/etc/telegraf
    depends_on:
      - influxdb
