networks:
  ml_net:
    driver: bridge

volumes:
  influx_data:
  mosquitto_log:
  mosquitto_data:
  rabbitmq_data:
  rabbitmq_log:

services:
  influxdb:
    image: influxdb:1.8.10-alpine
    networks:
      - ml_net
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - ./docker-volumes/influxdb/config:/etc/influxdb

  telegraf:
    build: components/telegraf
    networks:
      - ml_net
    volumes:
      - ./docker-volumes/telegraf/config:/etc/telegraf
    depends_on:
      - influxdb
      - mosquitto
      - rabbitmq
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - ml_net
    ports:
      - 1883:1883
    volumes:
      - ./docker-volumes/mosquitto/config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
      - mosquitto_data:/mosquitto/data


  rabbitmq: # long starting time
    image: rabbitmq:3.11.3-management-alpine
    networks:
      - ml_net
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - ./docker-volumes/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  grafana:
    image: grafana/grafana
    networks: 
      - ml_net
    ports:
      - 3000:3000
    volumes:
      - ./docker-volumes/grafana:/var/lib/grafana
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
    depends_on:
      - influxdb
      
  preprocessor:
    build: 
      dockerfile: ./components/preprocessor/Dockerfile
      context: ./
    networks:
      - ml_net
    volumes:
      - ./components/preprocessor/app:/app # dev-opt
    depends_on:
      - influxdb
  
  modelserver:
    build:
      dockerfile: ./components/modelserver/Dockerfile
      context: ./
    networks:
      - ml_net
    volumes:
      - ./components/modelserver/app:/app # dev-opt
    depends_on:
      - influxdb