networks:
  ml_net:
    driver: bridge

volumes:
  influx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/influx/data
  influx_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/influx/config
  telegraf_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/telegraf/config
  chronograf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-volumes/mldeploy/chronograf
  # mosquitto_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /docker-volumes/mldeploy/mosquitto/config

services:
  influxdb:
    build: influxdb
    networks:
      - ml_net
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb

  telegraf:
    build: telegraf
    networks:
      - ml_net
    volumes:
      - telegraf_config:/etc/telegraf
    depends_on:
      - influxdb
      - mosquitto

  # mosquitto:
  #   build: mosquitto
  #   networks:
  #     - ml_net
  #   ports:
  #     - 1883:1883
  #   volumes:
  #     - mosquitto_config:/mosquitto/config

  chronograf:
    build: chronograf
    networks: 
      - ml_net
    ports:
      - 8888:8888
    volumes:
      - chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
      
  preprocessor:
    build: preprocessor
    networks:
      - ml_net
    depends_on:
      - influxdb
  
  modelserver:
    build: modelserver
    networks:
      - ml_net
    depends_on:
      - influxdb