version: "3"

networks:
  ml_net:
    driver: bridge

volumes:
  influx_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${HOME}/docker-volumes/mldeploy/influx/data
  influx_config:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${HOME}/docker-volumes/mldeploy/influx/config
  chronograf:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${HOME}/docker-volumes/mldeploy/chronograf
  # mosquitto_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /docker-volumes/mldeploy/mosquitto/config

services:
  influxdb:
    build: influxdb
    networks:
      - ml_net
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    restart: always

  telegraf:
    build: telegraf
    networks:
      - ml_net
    volumes:
      - $HOME/telegraf_config:/etc/telegraf
    restart: always
    depends_on:
      - influxdb

  # mosquitto:
  #   build: mosquitto
  #   networks:
  #     - ml_net
  #   ports:
  #     - 1883:1883
  #   volumes:
  #     - mosquitto_config:/mosquitto/config

  chronograf:
    build: chronograf
    networks: 
      - ml_net
    ports:
      - 8888:8888
    volumes:
      - chronograf:/var/lib/chronograf
    restart: always
    depends_on:
      - influxdb
      
  preprocessor:
    build: preprocessor
    networks:
      - ml_net
    restart: always
    depends_on:
      - influxdb
  
  modelserver:
    build: modelserver
    networks:
      - ml_net
    restart: always
    depends_on:
      - influxdb