# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.DataSourceGRPCService_pb2 as DataSourceGRPCService__pb2


class DataSourceProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestDataSourceValue = channel.unary_unary(
                '/ProtoDataSource.DataSourceProvider/RequestDataSourceValue',
                request_serializer=DataSourceGRPCService__pb2.DataRequest.SerializeToString,
                response_deserializer=DataSourceGRPCService__pb2.ValueData.FromString,
                )
        self.RequestDataSourceValueStream = channel.unary_stream(
                '/ProtoDataSource.DataSourceProvider/RequestDataSourceValueStream',
                request_serializer=DataSourceGRPCService__pb2.DataRequest.SerializeToString,
                response_deserializer=DataSourceGRPCService__pb2.ValueResult.FromString,
                )
        self.RequestDataSourceChangeStream = channel.unary_stream(
                '/ProtoDataSource.DataSourceProvider/RequestDataSourceChangeStream',
                request_serializer=DataSourceGRPCService__pb2.ChangeRequest.SerializeToString,
                response_deserializer=DataSourceGRPCService__pb2.ChangeResult.FromString,
                )


class DataSourceProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestDataSourceValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDataSourceValueStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDataSourceChangeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataSourceProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestDataSourceValue': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDataSourceValue,
                    request_deserializer=DataSourceGRPCService__pb2.DataRequest.FromString,
                    response_serializer=DataSourceGRPCService__pb2.ValueData.SerializeToString,
            ),
            'RequestDataSourceValueStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestDataSourceValueStream,
                    request_deserializer=DataSourceGRPCService__pb2.DataRequest.FromString,
                    response_serializer=DataSourceGRPCService__pb2.ValueResult.SerializeToString,
            ),
            'RequestDataSourceChangeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestDataSourceChangeStream,
                    request_deserializer=DataSourceGRPCService__pb2.ChangeRequest.FromString,
                    response_serializer=DataSourceGRPCService__pb2.ChangeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProtoDataSource.DataSourceProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataSourceProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestDataSourceValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProtoDataSource.DataSourceProvider/RequestDataSourceValue',
            DataSourceGRPCService__pb2.DataRequest.SerializeToString,
            DataSourceGRPCService__pb2.ValueData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestDataSourceValueStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ProtoDataSource.DataSourceProvider/RequestDataSourceValueStream',
            DataSourceGRPCService__pb2.DataRequest.SerializeToString,
            DataSourceGRPCService__pb2.ValueResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestDataSourceChangeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ProtoDataSource.DataSourceProvider/RequestDataSourceChangeStream',
            DataSourceGRPCService__pb2.ChangeRequest.SerializeToString,
            DataSourceGRPCService__pb2.ChangeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataSourceManipulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ManipulateData = channel.unary_unary(
                '/ProtoDataSource.DataSourceManipulator/ManipulateData',
                request_serializer=DataSourceGRPCService__pb2.ManipulationRequest.SerializeToString,
                response_deserializer=DataSourceGRPCService__pb2.ManipulationResult.FromString,
                )


class DataSourceManipulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ManipulateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataSourceManipulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ManipulateData': grpc.unary_unary_rpc_method_handler(
                    servicer.ManipulateData,
                    request_deserializer=DataSourceGRPCService__pb2.ManipulationRequest.FromString,
                    response_serializer=DataSourceGRPCService__pb2.ManipulationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProtoDataSource.DataSourceManipulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataSourceManipulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ManipulateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProtoDataSource.DataSourceManipulator/ManipulateData',
            DataSourceGRPCService__pb2.ManipulationRequest.SerializeToString,
            DataSourceGRPCService__pb2.ManipulationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
